"""
==========================================================
TradeSuite
engine/edition.py
==========================================================

GENERATED by installer/set_edition.py -- do not edit by hand.
Currently: internal
"""

from __future__ import annotations

NAME = "internal"
SHOW_TRAIL_STUDY = True
AUTO_CLOSE_DEFAULT = True
