"""
==========================================================
TradeSuite
installer/set_edition.py
==========================================================

Writes engine/edition.py for whichever edition is about to be built.
Run this immediately before pyinstaller, then run set_edition.py internal
again immediately after building a customer edition -- the source tree's
default must always be left on "internal" so a normal, unqualified
rebuild (the everyday `pyinstaller TradeSuite.spec` used for Gopinath's
own live-trading install) never silently ships the customer edition's
restrictions to him by accident.

Usage:
    python installer/set_edition.py internal
    python installer/set_edition.py customer
"""

from __future__ import annotations

import sys
from pathlib import Path

EDITION_FILE = Path(__file__).resolve().parent.parent / "engine" / "edition.py"

PROFILES = {
    "internal": {"NAME": "internal", "SHOW_TRAIL_STUDY": True, "AUTO_CLOSE_DEFAULT": True},
    "customer": {"NAME": "customer", "SHOW_TRAIL_STUDY": False, "AUTO_CLOSE_DEFAULT": False},
}


def write(profile: str) -> None:
    p = PROFILES[profile]
    EDITION_FILE.write_text(
        '"""\n'
        "==========================================================\n"
        "TradeSuite\n"
        "engine/edition.py\n"
        "==========================================================\n\n"
        "GENERATED by installer/set_edition.py -- do not edit by hand.\n"
        f'Currently: {profile}\n'
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f'NAME = "{p["NAME"]}"\n'
        f'SHOW_TRAIL_STUDY = {p["SHOW_TRAIL_STUDY"]}\n'
        f'AUTO_CLOSE_DEFAULT = {p["AUTO_CLOSE_DEFAULT"]}\n',
        encoding="utf-8",
    )
    print(f"engine/edition.py set to '{profile}'.")


if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in PROFILES:
        print(f"Usage: python {Path(__file__).name} {{{'|'.join(PROFILES)}}}", file=sys.stderr)
        raise SystemExit(1)
    write(sys.argv[1])
